# Generated by Django 4.2.1 on 2023-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('game_title_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('listing_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('negotiation_available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('fee_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='ListingNegotiations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'listing_negotiations',
            },
        ),
        migrations.CreateModel(
            name='ListingPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('sort_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'listing_pictures',
            },
        ),
    ]
