# Generated by Django 4.2.1 on 2023-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_listingpictures_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpictures',
            name='seller_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
