# Generated by Django 4.2.1 on 2023-06-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_listingpictures_seller_id'),
    ]

    operations = [
    ]
