# Generated by Django 4.2.1 on 2023-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230630_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpictures',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
