# Generated by Django 4.2.1 on 2023-07-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_listingpictures_deleted_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingNegotiations',
            new_name='PurchaseRequests',
        ),
        migrations.AlterModelTable(
            name='purchaserequests',
            table='purchase_requests',
        ),
    ]
