# Generated by Django 4.2.1 on 2023-07-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_listingnegotiations_purchaserequests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='negotiation_available',
            new_name='price_negotiation',
        ),
    ]
