# Generated by Django 4.2.1 on 2023-07-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_negotiation_available_listing_price_negotiation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Listings',
        ),
        migrations.AlterModelTable(
            name='listings',
            table='listings',
        ),
    ]
