# Generated by Django 4.2.1 on 2023-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_listing_listings_alter_listings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequests',
            name='canceled_by',
            field=models.IntegerField(null=True),
        ),
    ]
