# Generated by Django 4.2.1 on 2023-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_purchaserequests_canceled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequests',
            name='price_in_negotiation',
            field=models.IntegerField(null=True),
        ),
    ]
