# Generated by Django 4.2.1 on 2023-08-25 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_purchaserequests_price_in_negotiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_request_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('message', models.TextField()),
                ('picture', models.CharField(max_length=255)),
                ('read', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_request_messages',
            },
        ),
    ]
