# Generated by Django 4.2.1 on 2023-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_purchaserequestmessages_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('game_title_id', models.IntegerField()),
                ('category', models.IntegerField()),
                ('request_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('fee_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
