# Generated by Django 4.2.1 on 2023-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_requests_fee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('contractor_id', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('status', models.IntegerField()),
                ('canceled_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'accepts',
            },
        ),
    ]
