# Generated by Django 4.2.1 on 2023-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_accepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepts',
            name='fee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accepts',
            name='price_in_negotiation',
            field=models.IntegerField(null=True),
        ),
    ]
