# Generated by Django 4.2.1 on 2023-09-26 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_accepts_fee_id_accepts_price_in_negotiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('message', models.TextField(null=True)),
                ('picture', models.CharField(max_length=255, null=True)),
                ('read', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accept_messages',
            },
        ),
    ]
